### ISSUE TITLE
General master

### ISSUE THREAD

**Issue by hrchlhck** [G5BCC/fire-detection-system#1]

**Comment by JuliaProkofiev** [comment]
#include <SoftwareSerial.h>

/*
First Slave:
TX = digital pin 10, RX = digital pin 11
Secons slave:
TX = digital pin 8, RX = digital pin 9
Third slave:
TX = digital pin 6, RX = digital pin 7
Fourth slave:
TX = digital pin 4, RX = digital pin 5

*/
int const FIRST_SLAVE_RX = 10;
int const FIRST_SLAVE_TX = 11;
int const SECOND_SLAVE_RX = 8;
int const SECOND_SLAVE_TX = 9;
int const THIRD_SLAVE_RX = 6;
int const THIRD_SLAVE_TX = 7;
int const FOURTH_SLAVE_RX = 4;
int const FOURTH_SLAVE_TX = 5;


// LED SLAVES ON MASTER
int const ANALOG_LED_FIRST_SLAVE = 0;
int const ANALOG_LED_SECOND_SLAVE = 1;
int const ANALOG_LED_THIRD_SLAVE = 2;
int const ANALOG_LED_FOURTH_SLAVE = 3;

SoftwareSerial firstSlave(FIRST_SLAVE_RX, FIRST_SLAVE_TX);
SoftwareSerial secondSlave(SECOND_SLAVE_RX, SECOND_SLAVE_TX);
SoftwareSerial thirdSlave(THIRD_SLAVE_RX, THIRD_SLAVE_TX);
SoftwareSerial fourthSlave(FOURTH_SLAVE_RX, FOURTH_SLAVE_TX);

SoftwareSerial slaves[4] = { firstSlave, secondSlave, thirdSlave, fourthSlave };
// Slaves states
enum {
	SEM_RESPOSTA,
	SEM_EMERGENCIA,
	ALERTA,
	ALERTA_A,
	EMERGENCIA,
	EMERGENCIA_A
};

int SLAVES_STATES[4] = {
	SEM_EMERGENCIA,
  	SEM_EMERGENCIA,
	SEM_EMERGENCIA,
	SEM_EMERGENCIA,
};
// Not response counter

int counters[4] = { 0,0,0,0 };

// Data receive/transmit
char c;
int ch = 0;
String recData;

void initializeSlavesSerials() {
	for (int i = 0; i < 4; i++) {
		slaves[i].begin(9600);
	}
}


void initializeSlaves() {
	initializeSlaves();

	pinMode(FIRST_SLAVE_RX, INPUT);
	pinMode(FIRST_SLAVE_TX, OUTPUT);
  	pinMode(ANALOG_LED_FIRST_SLAVE, OUTPUT);

	pinMode(SECOND_SLAVE_RX, INPUT);
	pinMode(SECOND_SLAVE_TX, OUTPUT);
  	pinMode(ANALOG_LED_SECOND_SLAVE, OUTPUT);

	pinMode(THIRD_SLAVE_RX, INPUT);
	pinMode(THIRD_SLAVE_TX, OUTPUT);
  	pinMode(ANALOG_LED_THIRD_SLAVE, OUTPUT);

	pinMode(FOURTH_SLAVE_RX, INPUT);
	pinMode(FOURTH_SLAVE_TX, OUTPUT);
  	pinMode(ANALOG_LED_FOURTH_SLAVE, OUTPUT);
}

void setInterval() {
	delay(200);
}


/*
	Função para quando não há nenhuma emergencia do slave
	paramêtro:
		int id: específica o id do slave
	pseudo código:
		sobrescreve o estado do slave específicado para "SEM_EMERGENCIA"

*/
void semEmergencia(int id) {
	SLAVES_STATES[id] = SEM_EMERGENCIA;
	switch (id)
	{ // Desliga leds ativos.
	case 0:
		analogWrite(ANALOG_LED_FIRST_SLAVE, LOW);
	case 1:
		analogWrite(ANALOG_LED_SECOND_SLAVE, LOW);
      	break;
	case 2:
		analogWrite(ANALOG_LED_THIRD_SLAVE, LOW);
      	break;
	case 3:
		analogWrite(ANALOG_LED_FOURTH_SLAVE, LOW);
      	break;
	default:
		break;
	}
}

/*
	Função para quando não teve nenhuma resposta do slave
	paramêtro:
		int id: específica o id do slave
	pseudo código:
		adiciona um no contador se o número de chamadas for menor que 3;
		caso seja igual ou maior a tres, o estado para o slave em específico irá para "SEM_RESPOSTA".
*/
void semResposta(int id) {
	if (counters[id] < 3) {
		counters[id]++;
	}
	else {
		SLAVES_STATES[id] = SEM_RESPOSTA;
		chamarTecnico(id);
	}
}

void chamarTecnico(int id) {
  for (int i=0; i<4;i++){
	if (SLAVES_STATES[id] == SEM_RESPOSTA) {
		Serial.write("Problema com o equipamento, solicitar tecnico./n");
      	counters[id] = 0;
	}else { //verificação sistema slave's
		semResposta(id);
      	break;
	};
  }
}

void emitirAlerta(int id) {
	SLAVES_STATES[id] = ALERTA;
  	counters[id] = 2;
	switch (id) //ligar leds ALERTA master
	{
	case 0:
		analogWrite(ANALOG_LED_FIRST_SLAVE, 255);
      	break;
	case 1:
		analogWrite(ANALOG_LED_SECOND_SLAVE, 255);
      	break;
	case 2:
		analogWrite(ANALOG_LED_THIRD_SLAVE, 255);
      	break;
	case 3:
		analogWrite(ANALOG_LED_FOURTH_SLAVE, 255);
      	break;
	default:
		break;
	}
  	delay(6000); 
  	SLAVES_STATES[id] = ALERTA_A; //Chamado sendo atendido
  
	/* TODO: uma função que ativa algum dispositivo que emite um alerta para os bombeiros
	Requisitos: deve-se informar qual é o slave que está em alerta
	*/
}


/*
	Função para quando há uma mensagem de alerta
	paramêtro:
		int id: específica o id do slave
	pseudo código:
		se o estado do slave especifico for alerta,
			toca o sinal.
		se o estado do slave especifico for um alerta atendido,
			aguarda.
		se nenhuma das ocorrencias for atendido,
			estado do slave é sobrescrito para ALERTA e o sinal é tocado.
*/
void slaveAlerta(int id) {

	// Para a primeira ocorrencia do alerta
	switch (SLAVES_STATES[id])
	{
	case ALERTA:
		emitirAlerta(id);
		break;
	case ALERTA_A:
		break;
	default:
		SLAVES_STATES[id] = ALERTA;
		emitirAlerta(id);
		break;
	}
}

/*
	Função para quando há uma mensagem de emergência
	paramêtro:
		int id: específica o id do slave
	pseudo código:
	se o estado do slave especifico for emergencia,
			toca o sinal.
		se o estado do slave especifico for um emergencia atendido,
			aguarda.
		se nenhuma das ocorrencias for atendido,
			estado do slave é sobrescrito para EMERGENCIA e o sinal é tocado.
*/
void slaveEmergencia(int id) {
	// Para a primeira ocorrencia da emergência
	switch (SLAVES_STATES[id])
	{
	case EMERGENCIA:
		emitirAlerta(id); 
		break;
	case EMERGENCIA_A: // TODO: Precisa ter um botão para alterar o estado de emergencia
		break;
	default:
		SLAVES_STATES[id] = EMERGENCIA;
		emitirAlerta(id);
		break;
	}
}

void listen(int id) {
  slaves[id].listen();
  if(slaves[id].isListening()) {
    if(slaves[id].available() > 0) {
    	recData = "";
       while(slaves[id]){
        c = slaves[id].read();
        recData += c;
      }
    }
  }
  delay(500);
}


void ReadSlaves(int id){
    listen(id);
    int lastChar = recData.length() - 1;
    if(recData.charAt(lastChar) == '1') {
      counters[id] == 1; 
    } else {
      counters[id] == 0;
    }
    Serial.println(recData);
}


void slaveRotina(int id) {
  	ReadSlaves(id);
	switch (counters[id]) // entrada dos dados
	{
	case 0:
		semEmergencia(id);
		break;
	case 1:
		slaveEmergencia(id);
		break;
	case 2:
		slaveAlerta(id);
		break;
	default:
		semResposta(id);
		break;
	}
}

void setup() {
    Serial.begin(9600);
	initializeSlaves(); 
}

void loop() {
	slaveRotina(0);// Generalizar
  	setInterval();
  	slaveRotina(1);
  	setInterval();
  	slaveRotina(2);
  	setInterval();
  	slaveRotina(3);
	setInterval();
}
